id = "soppo"
name = "Soppo"
version = "0.1.0"
schema_version = 1
description = "Soppo language support for Zed"
authors = ["Justin Duch"]
repository = "https://github.com/halcyonnouveau/soppo"

[grammars.soppo]
repository = "https://github.com/halcyonnouveau/soppo"
rev = "9fb6e13e214d741326ee412b6625624d2a38b6d6"
path = "editors/tree-sitter"

[language_servers.soppo-lsp]
name = "Soppo LSP"
languages = ["Soppo"]
