id = "soppo"
name = "Soppo"
version = "0.1.0"
schema_version = 1
description = "Soppo language support for Zed"
authors = ["Justin Duch"]
repository = "https://github.com/halcyonnouveau/soppo"

[grammars.soppo]
repository = "https://github.com/halcyonnouveau/soppo"
rev = "20095abe01dd5294d2fe46af1c4b7d15edf6bf7e"
path = "editors/tree-sitter"

[grammars.toml]
repository = "https://github.com/tree-sitter/tree-sitter-toml"
rev = "342d9be207c2dba869b9967124c679b5e6fd0ebe"

[language_servers.sopls]
name = "Soppo Language Server"
languages = ["Soppo"]
