[package]
name = "sopls"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Language server for Soppo"

[[bin]]
name = "sopls"
path = "src/main.rs"

[dependencies]
soppo = { workspace = true }
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
miette = "7.6"

[dev-dependencies]
tower = "0.5"
futures = "0.3"
