import { createTheme } from "@uiw/codemirror-themes";
import { tags as t } from "@lezer/highlight";

// Ayu Dark color palette (modified to match page background)
export const ayuDark = createTheme({
  theme: "dark",
  settings: {
    background: "#1a1a1a",
    foreground: "#bfbdb6",
    caret: "#e6b450",
    selection: "#409fff66",
    selectionMatch: "#409fff44",
    lineHighlight: "#222222",
    gutterBackground: "#1a1a1a",
    gutterForeground: "#505050",
    gutterBorder: "transparent",
  },
  styles: [
    { tag: t.comment, color: "#636a72" },
    { tag: t.lineComment, color: "#636a72" },
    { tag: t.blockComment, color: "#636a72" },
    { tag: t.docComment, color: "#636a72" },
    { tag: t.name, color: "#bfbdb6" },
    { tag: t.variableName, color: "#bfbdb6" },
    { tag: t.definition(t.variableName), color: "#bfbdb6" },
    { tag: t.function(t.variableName), color: "#ffb454" },
    { tag: t.typeName, color: "#59c2ff" },
    { tag: t.tagName, color: "#59c2ff" },
    { tag: t.propertyName, color: "#59c2ff" },
    { tag: t.attributeName, color: "#ffb454" },
    { tag: t.keyword, color: "#ff8f40" },
    { tag: t.modifier, color: "#ff8f40" },
    { tag: t.operatorKeyword, color: "#ff8f40" },
    { tag: t.controlKeyword, color: "#ff8f40" },
    { tag: t.definitionKeyword, color: "#ff8f40" },
    { tag: t.moduleKeyword, color: "#ff8f40" },
    { tag: t.operator, color: "#f29668" },
    { tag: t.special(t.string), color: "#e6b673" },
    { tag: t.string, color: "#aad94c" },
    { tag: t.number, color: "#d2a6ff" },
    { tag: t.integer, color: "#d2a6ff" },
    { tag: t.float, color: "#d2a6ff" },
    { tag: t.bool, color: "#d2a6ff" },
    { tag: t.null, color: "#d2a6ff" },
    { tag: t.regexp, color: "#95e6cb" },
    { tag: t.escape, color: "#95e6cb" },
    { tag: t.punctuation, color: "#bfbdb6" },
    { tag: t.bracket, color: "#bfbdb6" },
    { tag: t.invalid, color: "#ff3333" },
  ],
});
